// This script adds exampleZh to words14.js entries that are missing them
const fs = require('fs');
const path = require('path');

// Comprehensive translation mapping for all examples missing exampleZh
const translationMap = {
  "Dealing with rejection is never easy but it makes you stronger.": "處理被拒絕從來都不容易，但它會讓你變得更強大。",
  "He is afraid of commitment and avoids serious relationships.": "他害怕承諾，避免認真的關係。",
  "A good relationship requires compromise from both sides.": "一段好的關係需要雙方的妥協。",
  "You need to set clear boundaries with people who take advantage of you.": "你需要與利用你的人設定明確的界線。",
  "They have been in a situationship for months without defining anything.": "他們處於曖昧關係好幾個月，什麼都沒有定義。",
  "I always feel like a third wheel when I hang out with couples.": "當我和情侶一起出去時，我總是感覺像個電燈泡。",
  "He asked his best friend to be his wingman at the party.": "他請他最好的朋友在派對上做他的僚機。",
  "Their bromance is so strong that they go everywhere together.": "他們的兄弟情非常深厚，他們走到哪裡都在一起。",
  "She is my frenemy; we smile at each other but secretly compete.": "她是我亦敵亦友的人；我們相互微笑，但暗自競爭。",
  "Our relationship is strictly platonic; we are just very close friends.": "我們的關係純粹是友誼的；我們只是非常親密的朋友。",
  "They shared an intimate dinner at a quiet little restaurant.": "他們在一家安靜的小餐廳享用了親密的晚餐。",
  "The teacher used a fun icebreaker game on the first day of class.": "老師在課堂第一天使用了有趣的破冰遊戲。",
  "I am terrible at small talk and never know what to say.": "我很不擅長閒聊，從不知道該說什麼。",
  "She gave me a sweet compliment about my new haircut today.": "她今天給了我一個關於我新髮型的甜蜜讚美。",
  "I hate confrontation so I try to avoid arguments whenever possible.": "我討厭對質，所以盡可能避免爭論。",
  "I cannot believe she would backstab me after all these years.": "我不敢相信她在這些年後竟然會背後捅我。",
  "He felt deeply hurt when his best friend decided to betray him.": "當他最好的朋友決定背叛他時，他感到很傷心。",
  "She dumped him immediately after she found out he was cheating.": "她發現他劈腿後立即甩了他。",
  "We are going on our third date to that Italian place downtown.": "我們要去市中心那家義大利餐廳進行第三次約會。",
  "They went to the Maldives for their honeymoon after the wedding.": "他們在婚禮後去馬爾地夫度蜜月。",
  "The restaurant has such a romantic atmosphere that makes you want to stay forever.": "這家餐廳的氛圍是如此浪漫，讓你想永遠呆在那裡。",
  "She was never satisfied with anything he did so they broke up.": "她對他做的任何事情都不滿意，所以他們分手了。",
  "After years of marriage they decided to renew their vows.": "經過多年的婚姻，他們決定重新宣誓他們的誓言。",
  "I have been single for so long that I forgot how to date.": "我單身這麼久，都忘記怎麼約會了。",
  "He always flirts with the cute girl at the gym but never actually talks to her.": "他總是和健身房裡的漂亮女孩調情，但從不真正和她交談。",
  "They have no chemistry together so their relationship did not work out.": "他們之間沒有化學反應，所以他們的關係沒有成功。",
  "She hides her relationship on social media because she is afraid of judgment.": "她在社交媒體上隱藏她的關係，因為她害怕被評判。",
  "His ex-girlfriend keeps texting him which makes his current girlfriend jealous.": "他的前女友一直在給他發訊息，這讓他現在的女友很嫉妒。",
  "We have been together so long that we finish each other's sentences.": "我們在一起這麼久了，以至於我們能接對方的句子。",
  "Long distance relationships are hard but many couples make them work.": "遠距離戀愛很困難，但許多情侶成功了。",
  "He sent her a heartfelt message after their first kiss.": "他在他們第一次親吻後給她發送了一條深情的訊息。",
  "Their wedding was so beautiful that everyone cried happy tears.": "他們的婚禮是如此美麗，以至於每個人都流下了開心的淚水。",
  "She told him that she needed some space to figure things out.": "她告訴他她需要一些空間來理清事情。",
  "Dating someone new can be scary but also exciting.": "和新對象約會可能很可怕，但也很興奮。",
  "They have been married for thirty years and still act like newlyweds.": "他們已經結婚三十年，仍然表現得像新婚夫婦。",
  "I saw him with another girl and was shocked; he denied cheating though.": "我看到他和另一個女孩在一起，我感到震驚；但他否認了劈腿。",
  "Some people get married too quickly without really knowing their partner.": "有些人結婚太快，沒有真正了解他們的伴侶。",
  "She is considering breaking up with him because of his bad temper.": "她正在考慮因為他的脾氣暴躁而和他分手。",
  "After the fight they did not talk for a whole week; it was terrible.": "打架後他們整整一周沒有說話；那很可怕。",
  "Being in love makes you do crazy things you never thought you would do.": "戀愛會讓你做瘋狂的事情，你從未想過你會做。",
  "The couple had different goals in life so they parted ways amicably.": "這對夫婦在人生中有不同的目標，所以他們友好地分道揚鑣。",
  "He promised her forever but left her after just two years.": "他承諾永遠，但在兩年後離開了她。",
  "She feels pressured by her family to get married soon.": "她感到家人催促她儘快結婚的壓力。",
  "They dated for five years before deciding to finally get married.": "他們約會五年後才決定最終結婚。",
  "His biggest fear is losing her so he holds on too tight sometimes.": "他最大的恐懼是失去她，所以他有時抱得太緊了。",
  "A successful relationship is built on trust and open communication.": "成功的關係建立在信任和開放溝通的基礎上。",
  "They decided to elope because they wanted a simple private ceremony.": "他們決定私奔是因為他們想要一個簡單的私人儀式。",
  "Try to mingle with other guests instead of staying in the corner.": "試著和其他客人社交，而不是待在角落裡。",
  "We really bonded during the road trip and became close friends.": "我們在公路旅行中真的建立了感情，成為了親密的朋友。",
  "We are having a casual get-together at my place this Friday night.": "我們本周五晚上在我家舉辦一個隨性的小聚會。",
  "Our neighbor always plays loud music late at night and it drives me crazy.": "我們的鄰居總是在深夜播放大聲的音樂，這讓我瘋狂。",
  "I commute forty minutes each way to work every single day.": "我每天通勤往返工作地點，每邊要四十分鐘。",
  "I need to run a few errands before the stores close today.": "我需要在商店今天關閉前跑幾個差事。",
  "Nobody likes doing chores but the house will not clean itself.": "沒人喜歡做家務，但房子不會自己打掃。",
  "I need to pick up some groceries on the way home tonight.": "我需要在今晚回家的路上買些食品雜貨。",
  "I have been putting off doing the laundry for three days now.": "我已經拖延洗衣服三天了。",
  "Can you vacuum the living room before our guests arrive tonight?": "我們的客人今晚到達前，你能吸塵客廳嗎？",
  "Just microwave the leftovers for two minutes and they will be ready.": "只需將剩菜微波加熱兩分鐘，它們就會準備好。",
  "Load the dishwasher after dinner so the kitchen stays clean.": "晚餐後裝入洗碗機，廚房會保持清潔。",
  "She spent the whole weekend reorganizing her wardrobe for the new season.": "她花了整個周末為新季節重新整理她的衣櫥。",
  "My closet is so full that I cannot fit anything else in there.": "我的衣櫃滿得我放不了任何東西。",
  "Check the pantry to see if we still have pasta and canned tomatoes.": "檢查食物儲藏室看我們是否仍然有義大利麵和罐裝番茄。",
  "We always go out for brunch on Sunday mornings with our friends.": "我們總是在周日早上和朋友一起出去吃早午餐。",
  "I am too tired to cook so let us just order takeout tonight.": "我太累了，無法烹飪，所以我們今晚就點外帶吧。",
  "We can have the leftovers from last night for lunch today.": "我們可以用昨晚剩下的食物當今天的午餐。",
  "She found an amazing recipe for chocolate cake on that food blog.": "她在那個美食博客上找到了一個驚人的巧克力蛋糕食譜。",
  "Make sure you have all the ingredients before you start cooking.": "開始烹飪前確保你有所有的食材。",
  "This dish needs more seasoning because it tastes a little bland.": "這道菜需要更多調味料，因為它嚐起來有點平淡。",
  "She only buys organic vegetables even though they cost a lot more.": "她只買有機蔬菜，儘管它們的成本更高。",
  "He went vegan last year and says he has never felt better.": "他去年開始吃純素，說他從未感覺更好。",
  "I try to fit in a quick workout before work every morning.": "我每天早上都試著在工作前擠出時間快速健身。",
  "She goes jogging in the park every evening to clear her head.": "她每晚都在公園裡慢跑以清空她的頭腦。",
  "Yoga has really helped me become more flexible and less stressed.": "瑜伽確實幫助我變得更靈活，壓力也更少。",
  "She practices meditation every morning to start the day with calm.": "她每天早上都冥想以平靜地開始新的一天。",
  "She has a ten-step skincare routine that she does every night.": "她每晚都做一個十步的護膚程序。",
  "Apply moisturizer right after washing your face for best results.": "洗臉後立即塗抹保濕乳液以獲得最佳效果。",
  "Do not forget to put on sunscreen before going to the beach.": "去海灘前不要忘記塗防曬乳。",
  "I need to get a haircut soon because my hair is getting too long.": "我需要盡快剪頭髮，因為我的頭髮變太長了。",
  "She treats herself to a manicure every other week at the salon.": "她每兩周到沙龍做一次美甲犒勞自己。",
  "She is doing a three-day juice detox to reset her body.": "她正在進行三天果汁排毒來重置她的身體。",
  "My allergy to pollen makes spring the worst season for me.": "我對花粉的過敏使春天對我來說最糟。",
  "She has been suffering from insomnia and barely sleeps at night.": "她一直受失眠困擾，晚上幾乎睡不著。",
  "He had a terrible hangover after drinking too much at the party.": "他在派對上喝太多後宿醉很嚴重。",
  "I try to avoid caffeine after three in the afternoon.": "我試著在下午三點以後避免咖啡因。",
  "I overslept this morning and almost missed my first class.": "我今早睡過頭，幾乎錯過了我的第一堂課。",
  "She can multitask like a pro while managing the kids and cooking.": "她在照顧孩子和烹飪的同時，能像專家一樣多任務處理。",
  "I spent the entire weekend trying to declutter my apartment.": "我花了整個周末試圖整理我的公寓。",
  "They plan to renovate the kitchen before moving into the house.": "他們計劃在搬入房子前翻新廚房。",
  "The kitchen is fully equipped with all modern appliances.": "廚房配備了所有現代家電。",
  "I canceled my gym subscription because I never actually went there.": "我取消了我的健身房訂閱，因為我從未真正去過那裡。",
  "She always checks for coupons before buying anything online.": "她在線上購買任何東西前總是檢查優惠券。",
  "This jacket was a real bargain at only fifteen dollars.": "這件夾克只要十五美元真是筆好買賣。",
  "I asked for a refund because the product arrived broken.": "我要求退款，因為產品到達時已經破損。",
  "Keep your receipt in case you need to return the item later.": "保留你的收據以防你以後需要退貨。",
  "I have been having a craving for chocolate cake all day.": "我整天都想吃巧克力蛋糕。",
  "She started counting calories to maintain a healthier diet.": "她開始計算卡路里以保持更健康的飲食。",
  "I make a banana and berry smoothie for breakfast every morning.": "我每天早上都做香蕉漿果果昔作為早餐。",
  "I need a double espresso to survive this Monday morning meeting.": "我需要雙份義式濃縮咖啡才能撐過星期一早上的會議。",
  "He always buys the latest gadgets even when he does not need them.": "他總是購買最新的小工具，即使他不需要它們。",
  "After a long day I like to unwind by watching my favorite show.": "在漫長的一天之後，我喜歡通過看我最喜歡的節目來放鬆。",
  "Remember to hydrate throughout the day especially in hot weather.": "記得全天補充水分，特別是在炎熱天氣。",
  "She likes to pamper herself with a long bath on Friday nights.": "她喜歡在周五晚上用長時間的沐浴犒勞自己。",
  "I ordered an iced oat milk latte from the new coffee shop.": "我從新咖啡館點了一份冰燕麥奶拿鐵。",
  "This bakery offers gluten-free options for people with sensitivities.": "這家麵包店為有過敏症的人提供無麩質選擇。",
  "You can find the snacks in aisle five next to the beverages.": "你可以在走道五找到零食，在飲料旁邊。",
  "The checkout line was so long that I waited for twenty minutes.": "結帳隊伍非常長，我等了二十分鐘。",
  "I do meal prep on Sundays so I have lunch ready all week.": "我在周日做備餐，所以我整周都有午餐準備好。",
  "I forgot my phone charger at home and my battery is almost dead.": "我把手機充電器忘在家裡了，我的電池幾乎沒電。",
  "The portions at that restaurant are huge so we always share.": "那家餐廳的份量很大，所以我們總是分享。",
  "She booked a pedicure appointment before wearing sandals this summer.": "她在今年夏天穿涼鞋前預訂了足部保養預約。",
  "I switched to decaf coffee because regular coffee gave me the jitters.": "我改喝低咖啡因咖啡，因為普通咖啡讓我發抖。",
  "We spent the whole weekend binge-watching that new Korean drama.": "我們花了整個周末一口氣追看那部新的韓國劇集。",
  "Do not tell me any spoilers because I have not seen it yet.": "不要告訴我任何劇透，因為我還沒看過。",
  "The sequel was disappointing because it could not match the original.": "續集令人失望，因為它無法匹敵原版。",
  "The prequel explains how the main character became a hero.": "前傳解釋了主角如何成為英雄的過程。",
  "The trailer for the new Marvel movie already has millions of views.": "新漫威電影的預告片已經有數百萬的點擊率。",
  "We are going to the movie premiere on opening night.": "我們要在首映之夜去看電影首映。",
  "The soundtrack of that movie is so good that I listen to it daily.": "那部電影的配樂非常好，我每天都聽。",
  "She bumped into a celebrity at the airport and got a photo.": "她在機場撞到一位名人並得到了一張照片。",
  "That influencer has over two million followers on social media.": "那位網紅在社交媒體上有超過兩百萬的粉絲。",
  "She gained a thousand new followers after her video went viral.": "她的影片瘋傳後獲得了一千名新粉絲。",
  "Her dance video went viral overnight and everyone was sharing it.": "她的舞蹈影片一夜之間瘋傳，每個人都在分享。",
  "That topic has been trending on social media for three days.": "該話題在社交媒體上已經流行三天了。",
  "He sent me a hilarious meme that perfectly described our Monday mood.": "他給我發了一個搞笑迷因，完美描述了我們的星期一心情。",
  "I listen to a true crime podcast during my commute every morning.": "我每天早上在通勤時聽真實犯罪播客。",
  "She does a livestream every Friday night to chat with her fans.": "她每周五晚上進行直播與粉絲聊天。",
  "Her cosplay outfit at the convention looked exactly like the character.": "她在展覽會上的角色扮演服裝看起來就像那個角色。",
  "The fandom went crazy when the band announced a reunion tour.": "當樂隊宣布重聚巡演時，粉絲圈瘋狂了。",
  "The romantic subplot was more interesting than the main story.": "浪漫的支線劇情比主故事更有趣。",
  "The season ended on a cliffhanger and I cannot wait for next year.": "該季節以懸念結尾結束，我等不及明年了。",
  "Horror is my least favorite genre because I scare easily.": "恐怖是我最不喜歡的類型，因為我很容易受驚。",
  "That sitcom has been on the air for over ten seasons now.": "那部情境喜劇已經播出十多季了。",
  "We watched an amazing documentary about ocean life last night.": "我們昨晚看了一部關於海洋生命的驚人紀錄片。",
  "Japanese animation has gained a massive global following in recent years.": "日本動畫近年來獲得了大量的全球追隨者。",
  "That summer blockbuster made over a billion dollars at the box office.": "那部夏季大片在票房上獲得了超過十億美元。",
  "The director made a surprise cameo in the last scene of the film.": "導演在電影的最後一幕做了一個驚喜客串。",
  "The remake was decent but fans still prefer the original version.": "翻拍版還不錯，但粉絲仍然喜歡原版。",
  "The studio announced a reboot of the classic superhero franchise.": "工作室宣布重啟經典超級英雄特許經營權。",
  "The spin-off series focuses on the villain's backstory and origin.": "衍生劇集專注於反派的背景和起源。",
  "Most people prefer streaming services over traditional cable television now.": "現在大多數人更喜歡流媒體服務而不是傳統有線電視。",
  "She made a chill playlist for studying that lasts over three hours.": "她為學習製作了一個超過三小時的平靜播放清單。",
  "We go to karaoke every Friday night and sing until midnight.": "我們每周五晚上去卡拉OK，唱到午夜。",
  "His stand-up special on streaming had everyone laughing nonstop.": "他的脫口秀特別節目讓每個人都不停地笑。",
  "She is obsessed with that dating reality show and watches every episode.": "她沉迷於那個約會實境節目，每集都看。",
  "The show was canceled because of low ratings after the second season.": "由於第二季的收視率低，該節目被取消。",
  "She nailed the audition and got the lead role in the musical.": "她試鏡表現完美，獲得了音樂劇的主角。",
  "The band made their debut with a sold-out concert in Seoul.": "樂隊以首爾的一場售罄演唱會進行了出道。",
  "The crowd kept screaming for an encore after the final song.": "在最後一首歌後，人群不斷尖叫要求安可。",
  "That indie band has finally broken into mainstream music this year.": "那個獨立樂隊今年終於進入了主流音樂。",
  "She prefers indie films over big Hollywood productions.": "她更喜歡獨立電影而不是大型好萊塢製作。",
  "The singer made an incredible comeback after five years of silence.": "歌手在五年沉寂後做了一次令人難以置信的復出。",
  "The band announced a hiatus so members could work on solo projects.": "樂隊宣布暫停，以便成員可以從事單飛項目。",
  "The show got canceled after fans discovered the host's old tweets.": "粉絲發現主持人的舊推文後，該節目被取消。",
  "She writes fanfiction about her favorite characters in her spare time.": "她在空閒時間寫她喜歡的角色的同人小說。",
  "The band sells tons of merchandise including shirts hats and posters.": "樂隊銷售大量周邊商品，包括襯衫、帽子和海報。",
  "The paparazzi followed the actress everywhere she went this week.": "狗仔隊這週跟蹤了女演員走的每一個地方。",
  "Do not believe everything you read in the tabloids about celebrities.": "不要相信你在名人八卦小報中讀到的一切。",
  "The scandal ruined his career and he disappeared from the public eye.": "這個醜聞毀掉了他的事業，他從公眾視野中消失了。",
  "She was a nominee for best actress at the awards ceremony.": "她是頒獎典禮上最佳女演員的被提名者。",
  "The choreography in that music video is absolutely incredible.": "那個音樂影片中的編舞絕對令人難以置信。",
  "He performed all his own stunts without using a body double.": "他執行了所有自己的特技動作，沒有使用替身。",
  "We had a movie marathon and watched all six films in one day.": "我們進行了電影馬拉松，在一天內看了所有六部電影。",
  "Let me give you a quick recap of last week's episode.": "讓我為你快速回顧一下上周的劇集。",
  "The teaser only showed ten seconds but it already looks amazing.": "預告片只顯示了十秒，但看起來已經很驚人。",
  "The blooper reel at the end of the movie was the best part.": "電影末尾的NG片段是最好的部分。",
  "She appeared on a late night talk show to promote her new book.": "她出現在深夜脫口秀節目上推廣她的新書。",
  "Fans celebrated when the network announced the show's renewal.": "當電視網宣布該節目續訂時，粉絲歡呼。",
  "She waited two hours in line just to get his autograph.": "她排隊等了兩個小時只是為了得到他的親筆簽名。",
  "All the stars looked stunning walking down the red carpet last night.": "所有明星昨晚在紅毯上行走時看起來驚艷。",
  "The film broke box office records on its opening weekend.": "該電影在開放周末打破了票房記錄。",
  "She discovered that underground band years before they became famous.": "她在那個地下樂隊出名前多年就發現了他們。",
  "I am literally dying of laughter right now watching this video.": "我現在看著這個影片真的要笑死了。",
  "She basically told me she does not want to be friends anymore.": "她基本上告訴我她不想再做朋友了。",
  "Honestly I do not care what other people think about my choices.": "說實話，我不在乎其他人對我選擇的看法。",
  "Apparently they broke up last week but nobody told me.": "聽說他們上周分手了，但沒人告訴我。",
  "She finally left that toxic relationship and feels so much better.": "她最終離開了那段不健康的關係，感覺好多了。",
  "This cafe has such a cozy vibe with the warm lights and music.": "這家咖啡館有溫暖燈光和音樂營造的舒適氛圍。",
  "Let us just chill at home tonight and watch a movie.": "我們就在家裡放鬆，今晚看電影吧。",
  "That old video of me singing at the party is so cringe.": "我在派對上唱歌的那部舊影片令人尷尬。",
  "Her comeback was absolutely savage and left everyone speechless.": "她的回應非常嗆辣，讓每個人都啞口無言。",
  "He is always flexing his new sneakers on social media.": "他總是在社交媒體上炫耀他的新運動鞋。",
  "I lowkey want to skip the party and stay in bed.": "我低調想跳過派對，待在床上。",
  "I am highkey obsessed with that new restaurant on Main Street.": "我超級沉迷於主街上的那家新餐廳。",
  "Seeing everyone at the concert gave me serious FOMO.": "看到所有在演唱會上的人讓我有嚴重的錯過恐懼症。",
  "She booked a spontaneous trip to Japan because YOLO right?": "她預訂了一趟去日本的自發性旅行，因為人生只有一次，對吧？",
  "The hype around that movie was huge but it turned out average.": "那部電影的炒作很大，但結果很平凡。",
  "She found out her online boyfriend was a catfish using fake photos.": "她發現她的線上男友是用假照片騙人的人。",
  "Just ignore the trolls in the comments section and move on.": "只需忽略評論部分中的網路酸民並繼續。",
  "My inbox is full of spam emails trying to sell me random stuff.": "我的收件箱滿是試圖賣我隨機東西的垃圾郵件。",
  "That article was total clickbait and had nothing useful inside.": "那篇文章純粹是標題黨，裡面沒有任何有用的內容。",
  "She added ten hashtags to her post hoping to get more likes.": "她在帖子上添加了十個主題標籤，希望獲得更多讚。",
  "We took a selfie together in front of the Eiffel Tower.": "我們在埃菲爾鐵塔前一起自拍。",
  "A random stranger photobombed our group picture at the park.": "一個陌生人在公園裡亂入了我們的集體照。",
  "She is such a foodie that she photographs every meal she eats.": "她是一個美食愛好者，她拍攝她吃的每一頓飯。",
  "My boss is a total workaholic who never takes a day off.": "我的老闆是個工作狂，從不休息。",
  "She admits she is a shopaholic and her closet proves it.": "她承認她是購物狂，她的衣櫃證明了這一點。",
  "I always procrastinate on big projects until the very last minute.": "我總是拖延大項目直到最後一刻。",
  "It was a real bummer that the concert got canceled last minute.": "演唱會在最後一刻被取消真是令人失望。",
  "That alley looks really sketchy so let us take another route.": "那條小巷看起來真的很可疑，讓我們走另一條路。",
  "That deal sounds pretty shady; I would not trust that website.": "那筆交易聽起來很可疑；我不會信任那個網站。",
  "Is this website legit or is it going to steal my credit card info?": "這個網站是真實的嗎，還是它會竊取我的信用卡信息？",
  "He is still salty about losing that basketball game last week.": "他仍然對上周輸掉那場籃球比賽感到不爽。",
  "She absolutely slayed in that red dress at the party last night.": "她昨晚在派對上穿著那件紅裙子超級帥翻了。",
  "Her Instagram feed has a very clean and minimalist aesthetic.": "她的Instagram摘要有非常乾淨和簡約的美感。",
  "She is a total stan and has been to every single concert.": "她是個超級粉絲，參加過每一場演唱會。",
  "The way he avoided the question was really sus if you ask me.": "如果你問我，他迴避這個問題的方式真的很可疑。",
  "His friends called him a simp for buying her flowers every day.": "他的朋友因為他每天給她買花而叫他舔狗。",
  "Some people do crazy things on the internet just for clout.": "有些人在互聯網上做瘋狂的事情只是為了影響力。",
  "She had the biggest glow-up after high school and looks amazing now.": "她在高中後經歷了最大的變身，現在看起來驚人。",
  "That was such a facepalm moment when he called her the wrong name.": "當他叫錯她的名字時，那真是一個無言以對的時刻。",
  "She went on a rant about how terrible the customer service was.": "她抱怨顧客服務有多糟糕。",
  "My friends love to roast me about my terrible cooking skills.": "我的朋友喜歡吐槽我可怕的烹飪技能。",
  "She posted a throwback photo from her college days on Instagram.": "她在Instagram上發佈了她大學時代的懷舊照片。",
  "I had to unfollow him because his posts were super annoying.": "我不得不取消對他的追蹤，因為他的帖子非常煩人。",
  "She slid into his DMs and they have been talking ever since.": "她滑入了他的私訊，從那時起他們一直在聊天。",
  "I spent an hour swiping on dating apps without finding anyone interesting.": "我花了一個小時在約會應用上滑動，但沒有找到任何有趣的人。",
  "I turned off all notifications so I could focus on studying.": "我關閉了所有通知以便能專注於學習。",
  "She uses so many filters that she looks completely different in person.": "她使用了太多濾鏡，以至於親自看起來完全不同。",
  "I took a screenshot of the message and sent it to my best friend.": "我截圖了訊息並發送給了我的好友。",
  "I wasted two hours scrolling through social media before bed again.": "我又浪費了兩個小時在睡前滾動瀏覽社交媒體。",
  "Do not forget to like and subscribe if you enjoyed this video.": "如果你喜歡這個影片，不要忘記點讚和訂閱。",
  "That tweet about hating Monday mornings is so relatable to everyone.": "那條關於討厭星期一早上的推文對每個人來說都有共鳴。",
  "That video of the grandpa learning to dance is so wholesome.": "那個祖父學習跳舞的影片太暖心了。",
  "That scene from the movie has become truly iconic in pop culture.": "電影中的那個場景已成為流行文化中真正的經典。",
  "She is so extra that she wore a ball gown to a casual dinner.": "她太浮誇了，以至於她穿著舞會禮服去參加隨性晚餐。",
  "That cat sleeping on the keyboard is such a mood on Mondays.": "那隻睡在鍵盤上的貓完全就是星期一的心情。",
  "Taking the free upgrade was a no-brainer for all of us.": "接受免費升級對我們所有人來說都是不用想也知道的事。",
  "Being rude to waiters is an absolute deal-breaker for me.": "對服務員無禮對我來說絕對是無法接受的條件。",
  "She started a side hustle selling handmade candles on the weekends.": "她開始了一個副業，在周末銷售手工蠟燭。",
  "Many fans consider him the GOAT of basketball with six championships.": "許多粉絲認為他是籃球史上最強者，擁有六次冠軍。",
  "He ghosted me after three great dates and I never heard from him.": "他在三次約會後突然人間蒸發，我再也沒聽到他的消息。",
};

const filePath = path.join(__dirname, 'server/data/words14.js');
const content = fs.readFileSync(filePath, 'utf8');

// Process the file
const lines = content.split('\n');
const updatedLines = [];

for (let i = 0; i < lines.length; i++) {
  let line = lines[i];

  // Check if line contains example but not exampleZh
  if (line.includes('example:') && !line.includes('exampleZh:')) {
    // Extract the example text
    const exampleMatch = line.match(/example: "([^"]+)"/);
    if (exampleMatch) {
      const example = exampleMatch[1];

      // Find the translation
      if (translationMap[example]) {
        // Replace the closing } with exampleZh and then close
        line = line.replace(' },', `, exampleZh: "${translationMap[example]}" },`);
      } else {
        console.log(`WARNING: No translation found for: "${example}"`);
      }
    }
  }

  updatedLines.push(line);
}

// Write the updated file
const updatedContent = updatedLines.join('\n');
fs.writeFileSync(filePath, updatedContent, 'utf8');

console.log('✓ Successfully added exampleZh to all missing entries!');
console.log(`Total lines processed: ${lines.length}`);
